version: '3.4'

services:

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest

  discountdb:
    image: postgres

  basketdata:
    image: redis:alpine
  
  mongo:
    image: "mongo"
    ports:
    - '27017-27019:27017-27019'

  rabbitmq:
    image: masstransit/rabbitmq

  catalog-api:
    image: ${REGISTRY:-eshop}/catalog.api-${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    depends_on:
      - sqldata

  basket-api:
    image: ${REGISTRY:-eshop}/basket.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    depends_on:
      - basketdata


  discount-api:
    image: ${REGISTRY:-eshop}/dsicount.api-${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile
    depends_on:
      - discountdb
      - rabbitmq


  ordering-api:
    image: ${REGISTRY:-eshop}/ordering.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
    depends_on:
      - sqldata
      - rabbitmq


  payemnt-api:
   image: ${REGISTRY:-eshop}/payment.api-${PLATFORM:-linux}-${TAG:-latest}
   build:
      context: .
      dockerfile: Services/Payment/Payment.API/Dockerfile
   depends_on:
      - rabbitmq