version: '3.4'

services:
 sqldata:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    volumes:
      - eshop-sqldata:/var/opt/mssql

 discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/


 catalog-api:
    env_file:
     - catalog.env 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=${ESHOP_CATALOG_DB:-Server=sqldata;Database=Services.CatalogDb;User Id=sa;Password=Pass@word}
      - PATH_BASE=${PATH_BASE}
      - SeqServerUrl=${SeqServerUrlVar}
      - LogstashgUrl=${LogstashUrlVar}
      - DiscountUrl=http://discount-api/api/Discount/
      - DiscountGrpcUrl=http://discount-api:81/
      - DiscountZerqUrl=tcp://discount-api:12345
      - GRPC_PORT=81
      - PORT=80
      - UseGrpc=true
    ports:
      - "5101:80"
      - "9101:81"

 discount-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=${ESHOP_AZURE_DISCOUNT_DB:-Server=discountdb;Port=5432;Database=servicesdiscountdb;User Id=admin;Password=admin1234;}
      - PATH_BASE=${PATH_BASE_Discount}
      - SeqServerUrl=${SeqServerUrlVar}
      - LogstashgUrl=${LogstashUrlVar}
      - GRPC_PORT=81
      - PORT=80
    ports:
      - "5102:80"
      - "9102:81"


volumes:
  eshop-sqldata:
    external: false
  postgres-data:
    external: false

